"""empty message

Revision ID: 5069e65e90bc
Revises: 189cdda4d434
Create Date: 2016-06-08 17:14:03.448694

"""

# revision identifiers, used by Alembic.
revision = '5069e65e90bc'
down_revision = '189cdda4d434'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
