"""postbody_html

Revision ID: ccf78b11c83d
Revises: 562e65de8b5e
Create Date: 2016-06-10 18:37:10.216308

"""

# revision identifiers, used by Alembic.
revision = 'ccf78b11c83d'
down_revision = '562e65de8b5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
