"""initial migration

Revision ID: cdc4a5ee8bf3
Revises: None
Create Date: 2016-06-06 16:03:10.190052

"""

# revision identifiers, used by Alembic.
revision = 'cdc4a5ee8bf3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
